<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
    <BlazorEnableCompression>true</BlazorEnableCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.0" PrivateAssets="all" />
    <PackageReference Include="Syncfusion.DocIO.Net.Core" Version="24.1.41" />
    <PackageReference Include="Syncfusion.DocIORenderer.Net.Core" Version="24.1.41" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="24.1.41" />
    <PackageReference Include="Syncfusion.Licensing" Version="24.1.41" />
  </ItemGroup>

</Project>
