using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace WordToPdfConverter.Services.Remediation.AI
{
    /// <summary>
    /// Executes remediation scripts generated by GPT-5 in a safe environment
    /// </summary>
    public class ScriptExecutor
    {
        private readonly ILogger<ScriptExecutor> _logger;
        private readonly string _scriptDirectory;

        public ScriptExecutor(ILogger<ScriptExecutor> logger)
        {
            _logger = logger;
            _scriptDirectory = Path.Combine(Path.GetTempPath(), "pdf-remediation-scripts");
            Directory.CreateDirectory(_scriptDirectory);
        }

        /// <summary>
        /// Execute a Python script for PDF remediation
        /// </summary>
        public async Task<ScriptResult> ExecutePythonScriptAsync(
            string script,
            byte[] inputPdf,
            string scriptType = "remediation")
        {
            var result = new ScriptResult();
            var sessionId = Guid.NewGuid().ToString("N");

            try
            {
                // Create session directory
                var sessionDir = Path.Combine(_scriptDirectory, sessionId);
                Directory.CreateDirectory(sessionDir);

                // Save input PDF
                var inputPath = Path.Combine(sessionDir, "input.pdf");
                var outputPath = Path.Combine(sessionDir, "output.pdf");
                var scriptPath = Path.Combine(sessionDir, "remediate.py");
                var logPath = Path.Combine(sessionDir, "execution.log");

                await File.WriteAllBytesAsync(inputPath, inputPdf);

                // Prepare the script with proper paths and error handling
                var fullScript = PrepareScript(script, inputPath, outputPath);
                await File.WriteAllTextAsync(scriptPath, fullScript);

                _logger.LogInformation($"[SCRIPT-EXECUTOR] Executing Python script in session {sessionId}");

                // Execute the script
                using var process = new Process
                {
                    StartInfo = new ProcessStartInfo
                    {
                        FileName = "python3",
                        Arguments = scriptPath,
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        UseShellExecute = false,
                        CreateNoWindow = true,
                        WorkingDirectory = sessionDir
                    }
                };

                var outputBuilder = new StringBuilder();
                var errorBuilder = new StringBuilder();

                process.OutputDataReceived += (sender, e) =>
                {
                    if (e.Data != null)
                    {
                        outputBuilder.AppendLine(e.Data);
                        _logger.LogDebug($"[SCRIPT-OUTPUT] {e.Data}");
                    }
                };

                process.ErrorDataReceived += (sender, e) =>
                {
                    if (e.Data != null)
                    {
                        errorBuilder.AppendLine(e.Data);

                        // Parse Python log level and log appropriately
                        var line = e.Data;
                        if (line.StartsWith("INFO:"))
                        {
                            _logger.LogInformation($"[SCRIPT-INFO] {line.Substring(5)}");
                        }
                        else if (line.StartsWith("WARNING:"))
                        {
                            _logger.LogWarning($"[SCRIPT-WARNING] {line.Substring(8)}");
                        }
                        else if (line.StartsWith("ERROR:") || line.StartsWith("CRITICAL:"))
                        {
                            _logger.LogError($"[SCRIPT-ERROR] {line}");
                        }
                        else if (line.StartsWith("DEBUG:"))
                        {
                            _logger.LogDebug($"[SCRIPT-DEBUG] {line.Substring(6)}");
                        }
                        else
                        {
                            // Unknown format, log as warning to be safe
                            _logger.LogWarning($"[SCRIPT-STDERR] {line}");
                        }
                    }
                };

                process.Start();
                process.BeginOutputReadLine();
                process.BeginErrorReadLine();

                // Wait for completion with timeout
                var completed = await Task.Run(() => process.WaitForExit(120000)); // 2 minute timeout

                if (!completed)
                {
                    process.Kill();
                    throw new TimeoutException("Script execution timed out");
                }

                result.ExitCode = process.ExitCode;
                result.StandardOutput = outputBuilder.ToString();
                result.StandardError = errorBuilder.ToString();
                result.Success = process.ExitCode == 0;

                // Save execution log
                var logContent = $"Exit Code: {result.ExitCode}\n\nOutput:\n{result.StandardOutput}\n\nErrors:\n{result.StandardError}";
                await File.WriteAllTextAsync(logPath, logContent);

                // Read output PDF if successful
                if (result.Success && File.Exists(outputPath))
                {
                    result.OutputPdf = await File.ReadAllBytesAsync(outputPath);
                    _logger.LogInformation($"[SCRIPT-EXECUTOR] Script completed successfully, output PDF size: {result.OutputPdf.Length} bytes");
                }
                else
                {
                    _logger.LogWarning($"[SCRIPT-EXECUTOR] Script failed or no output generated");
                }

                // Cleanup session directory (optional - keep for debugging)
                if (result.Success)
                {
                    try
                    {
                        Directory.Delete(sessionDir, true);
                    }
                    catch
                    {
                        // Ignore cleanup errors
                    }
                }

                return result;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "[SCRIPT-EXECUTOR] Script execution failed");
                result.Success = false;
                result.ErrorMessage = ex.Message;
                return result;
            }
        }

        /// <summary>
        /// Execute a C# script using dotnet-script or similar
        /// </summary>
        public async Task<ScriptResult> ExecuteCSharpScriptAsync(
            string script,
            byte[] inputPdf)
        {
            // Similar implementation for C# scripts
            // Could use Roslyn scripting API or dotnet-script CLI
            var result = new ScriptResult();

            _logger.LogWarning("[SCRIPT-EXECUTOR] C# script execution not yet implemented");
            result.Success = false;
            result.ErrorMessage = "C# script execution is not yet implemented";

            return result;
        }

        /// <summary>
        /// Prepare the script with proper imports and error handling
        /// </summary>
        private string PrepareScript(string script, string inputPath, string outputPath)
        {
            var sb = new StringBuilder();

            // Always add essential imports (needed for error handling)
            if (!script.Contains("import sys"))
            {
                sb.AppendLine("import sys");
            }
            if (!script.Contains("import os"))
            {
                sb.AppendLine("import os");
            }
            if (!script.Contains("import traceback"))
            {
                sb.AppendLine("import traceback");
            }
            sb.AppendLine();

            // Add input/output path variables
            sb.AppendLine($"INPUT_PDF = r'{inputPath}'");
            sb.AppendLine($"OUTPUT_PDF = r'{outputPath}'");
            sb.AppendLine();

            // Add the main script
            sb.AppendLine("try:");

            // Indent the user's script
            var lines = script.Split('\n');
            foreach (var line in lines)
            {
                sb.AppendLine($"    {line}");
            }

            // Add error handling
            sb.AppendLine("\nexcept Exception as e:");
            sb.AppendLine("    print(f'ERROR: {e}', file=sys.stderr)");
            sb.AppendLine("    traceback.print_exc(file=sys.stderr)");
            sb.AppendLine("    sys.exit(1)");

            // Ensure output file exists
            sb.AppendLine("\nif not os.path.exists(OUTPUT_PDF):");
            sb.AppendLine("    print('ERROR: Output PDF not created', file=sys.stderr)");
            sb.AppendLine("    sys.exit(1)");

            sb.AppendLine("\nprint(f'Successfully created {OUTPUT_PDF}')");
            sb.AppendLine("sys.exit(0)");

            return sb.ToString();
        }

        /// <summary>
        /// Install required Python packages if needed
        /// </summary>
        public async Task<bool> EnsurePythonDependenciesAsync()
        {
            try
            {
                // Check if required packages are installed
                var packages = new[] { "pikepdf", "PyPDF2", "reportlab", "pypdf" };

                foreach (var package in packages)
                {
                    var checkProcess = Process.Start(new ProcessStartInfo
                    {
                        FileName = "python3",
                        Arguments = $"-c \"import {package}\"",
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        UseShellExecute = false,
                        CreateNoWindow = true
                    });

                    await Task.Run(() => checkProcess.WaitForExit(5000));

                    if (checkProcess.ExitCode != 0)
                    {
                        _logger.LogInformation($"[SCRIPT-EXECUTOR] Installing Python package: {package}");

                        var installProcess = Process.Start(new ProcessStartInfo
                        {
                            FileName = "pip3",
                            Arguments = $"install {package}",
                            RedirectStandardOutput = true,
                            RedirectStandardError = true,
                            UseShellExecute = false,
                            CreateNoWindow = true
                        });

                        await Task.Run(() => installProcess.WaitForExit(60000));

                        if (installProcess.ExitCode != 0)
                        {
                            _logger.LogWarning($"[SCRIPT-EXECUTOR] Failed to install {package}");
                        }
                    }
                }

                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "[SCRIPT-EXECUTOR] Failed to ensure Python dependencies");
                return false;
            }
        }
    }

    public class ScriptResult
    {
        public bool Success { get; set; }
        public byte[] OutputPdf { get; set; }
        public string StandardOutput { get; set; }
        public string StandardError { get; set; }
        public int ExitCode { get; set; }
        public string ErrorMessage { get; set; }
    }
}