using Syncfusion.Pdf.Interactive;
using Syncfusion.Pdf.Parsing;
using System.Text.RegularExpressions;
using WordToPdfConverter.Models;

namespace WordToPdfConverter.Services
{
    public class FieldAnalysisService
    {
        public class FieldAnalysisResult
        {
            public bool ShouldKeep { get; set; }
            public string RecommendedAction { get; set; }
            public double ConfidenceScore { get; set; } // 0-1, higher = more confident
            public List<string> Reasons { get; set; } = new List<string>();
            public string Category { get; set; } // "DefinitelyKeep", "ProbablyKeep", "Uncertain", "ProbablyRemove", "DefinitelyRemove"
        }

        public class FieldProcessingConfig
        {
            public double RemovalThreshold { get; set; } = 0.7; // Only remove if confidence > 70%
            public bool ConservativeMode { get; set; } = true; // When in doubt, keep the field
            public bool IncludeVerySmallFields { get; set; } = false;
            public bool IncludeAutoGeneratedNames { get; set; } = false;
            public int MinFieldWidth { get; set; } = 10;
            public int MinFieldHeight { get; set; } = 8;
        }

        private readonly FieldProcessingConfig _config;

        public FieldAnalysisService(FieldProcessingConfig config = null)
        {
            _config = config ?? new FieldProcessingConfig();
        }

        public FieldAnalysisResult AnalyzeField(PdfLoadedField field)
        {
            var result = new FieldAnalysisResult
            {
                ConfidenceScore = 0.5, // Start neutral
                RecommendedAction = "Keep"
            };

            // Analyze field name
            AnalyzeFieldName(field, result);

            // Analyze field properties
            AnalyzeFieldProperties(field, result);

            // Analyze field positioning and size
            AnalyzeFieldGeometry(field, result);

            // Make final decision
            MakeFinalDecision(result);

            return result;
        }

        private void AnalyzeFieldName(PdfLoadedField field, FieldAnalysisResult result)
        {
            var name = field.Name ?? "";

            // Strong indicators of legitimate fields
            if (name.Contains("name") || name.Contains("date") || name.Contains("address") || 
                name.Contains("phone") || name.Contains("email") || name.Contains("ssn") ||
                name.Contains("signature") || name.Contains("amount") || name.Contains("check"))
            {
                result.ConfidenceScore += 0.3;
                result.Reasons.Add("Field name suggests legitimate form field");
                return;
            }

            // Check for auto-generated patterns
            if (string.IsNullOrWhiteSpace(name))
            {
                result.ConfidenceScore -= 0.4;
                result.Reasons.Add("Empty field name (likely auto-generated)");
            }
            else if (name.Length < 3)
            {
                result.ConfidenceScore -= 0.3;
                result.Reasons.Add("Very short field name");
            }
            else if (name.StartsWith("_"))
            {
                result.ConfidenceScore -= 0.3;
                result.Reasons.Add("Field name starts with underscore (system-generated)");
            }
            else if (name.Contains("unnamed"))
            {
                result.ConfidenceScore -= 0.4;
                result.Reasons.Add("Field name contains 'unnamed'");
            }
            else if (Regex.IsMatch(name, @"^Text\d{1,2}$"))
            {
                // Only penalize very short auto-generated Text fields
                if (name.Length <= 6)
                {
                    result.ConfidenceScore -= 0.2;
                    result.Reasons.Add("Short auto-generated Text field name");
                }
            }
            else if (name.Contains("field") && name.Contains("obj"))
            {
                result.ConfidenceScore -= 0.3;
                result.Reasons.Add("Field name contains 'field' and 'obj' (likely system-generated)");
            }
            else if (name.StartsWith("Textformfield"))
            {
                // These might be legitimate, just auto-named
                result.ConfidenceScore += 0.1;
                result.Reasons.Add("Textformfield prefix (possibly legitimate)");
            }
            else if (name.StartsWith("Check"))
            {
                // Checkbox fields are usually legitimate
                result.ConfidenceScore += 0.2;
                result.Reasons.Add("Checkbox field (likely legitimate)");
            }
        }

        private void AnalyzeFieldProperties(PdfLoadedField field, FieldAnalysisResult result)
        {
            // Required fields are more likely to be legitimate
            if (field.Required)
            {
                result.ConfidenceScore += 0.2;
                result.Reasons.Add("Field is marked as required");
            }

            // Fields with tooltips are more likely to be intentional
            if (!string.IsNullOrEmpty(field.ToolTip))
            {
                result.ConfidenceScore += 0.1;
                result.Reasons.Add("Field has tooltip/description");
            }

            // Different field types have different legitimacy probabilities
            if (field is PdfLoadedCheckBoxField)
            {
                result.ConfidenceScore += 0.1;
                result.Reasons.Add("Checkbox fields are typically intentional");
            }
            else if (field is PdfLoadedRadioButtonListField)
            {
                result.ConfidenceScore += 0.1;
                result.Reasons.Add("Radio buttons are typically intentional");
            }
            else if (field is PdfLoadedComboBoxField)
            {
                result.ConfidenceScore += 0.1;
                result.Reasons.Add("Dropdown fields are typically intentional");
            }
        }

        private void AnalyzeFieldGeometry(PdfLoadedField field, FieldAnalysisResult result)
        {
            if (field is PdfLoadedTextBoxField textField)
            {
                var bounds = textField.Bounds;

                // Very small fields are likely artifacts
                if (bounds.Width < _config.MinFieldWidth && bounds.Height < _config.MinFieldHeight)
                {
                    result.ConfidenceScore -= 0.4;
                    result.Reasons.Add($"Very small field ({bounds.Width:F0}x{bounds.Height:F0}) - likely formatting artifact");
                }

                // Fields in instruction areas (far left, very narrow)
                if (bounds.X < 30 && bounds.Width < 25)
                {
                    result.ConfidenceScore -= 0.2;
                    result.Reasons.Add("Field in left margin area (possibly instructional text)");
                }

                // Reasonable sized fields are more likely legitimate
                if (bounds.Width > 50 && bounds.Height > 15)
                {
                    result.ConfidenceScore += 0.1;
                    result.Reasons.Add("Reasonable field size for user input");
                }
            }
        }

        private void MakeFinalDecision(FieldAnalysisResult result)
        {
            // In conservative mode, only remove if we're very confident
            var threshold = _config.ConservativeMode ? 0.8 : _config.RemovalThreshold;

            if (result.ConfidenceScore >= 0.7)
            {
                result.ShouldKeep = true;
                result.Category = "DefinitelyKeep";
                result.RecommendedAction = "Keep - High confidence legitimate field";
            }
            else if (result.ConfidenceScore >= 0.3)
            {
                result.ShouldKeep = _config.ConservativeMode; // In conservative mode, keep uncertain fields
                result.Category = result.ShouldKeep ? "ProbablyKeep" : "Uncertain";
                result.RecommendedAction = result.ShouldKeep 
                    ? "Keep - Uncertain but conservative mode enabled"
                    : "Remove - Uncertain field";
            }
            else if (result.ConfidenceScore >= 0.1)
            {
                result.ShouldKeep = false;
                result.Category = "ProbablyRemove";
                result.RecommendedAction = "Remove - Likely false positive";
            }
            else
            {
                result.ShouldKeep = false;
                result.Category = "DefinitelyRemove";
                result.RecommendedAction = "Remove - High confidence false positive";
            }

            // Override for configuration settings
            if (!_config.IncludeVerySmallFields && result.Reasons.Any(r => r.Contains("Very small field")))
            {
                result.ShouldKeep = false;
                result.RecommendedAction = "Remove - Very small fields disabled in config";
            }

            if (!_config.IncludeAutoGeneratedNames && result.Reasons.Any(r => r.Contains("auto-generated")))
            {
                result.ShouldKeep = false;
                result.RecommendedAction = "Remove - Auto-generated names disabled in config";
            }
        }
    }
}
